### ISSUE TITLE
Make ssh_key optional on linux machines

### ISSUE THREAD

**Issue by scarolan** [Azure/terraform-azurerm-compute#101]
There are some use cases (training, development, etc) where users might prefer a simple username and password to access a linux virtual machine.  Currently there's no way to disable the `ssh_key` parameter even if you prefer to use a username and password.

**Comment by GMinchAQ** [comment]
Confirmed -- it ignores admin_username, and always configures ssh.  1.2.1 automatically looks in your ~/.ssh for id*.pub to use as the key unless you explicitly pass an ssh path.  You need to generate an ssh key pair before using the compute module. 

If you want to change it the behavior, you'd need to modify your compute module to set os_profile_linux_config {
    disable_password_authentication=false. 

I don't know if this can be considered a bug, but it is undocumented behavior and a breaking change from previous versions.
