### ISSUE TITLE
Remove network security group automatic creation for port 22

### ISSUE THREAD

**Issue by uthng** [Azure/terraform-azurerm-compute#103]
This role creates automatically a network security group for port 22 and attaches NIC to it to allow remote connection. It is good if we only have a VM and we do have only the 22 port rule.  If we want to attach VM's NIC or VM's subnet to another NSG because we want to open more ports and we cannot modify the automatic 22-NSG, it does not work anymore. Obviously, a VM can be in one and only one NSG.

I think we can always keep this feature for users who just want to create a VM and connect to it for test. In this case, `remote_port` variable must be specified. Otherwise, no NSG is created and in the `azurerm_network_interface`, the attribute `network_security_group_id` is not specified neither.

I can fix it if you are interessed in this request.

**Comment by yupwei68** [comment]
hi @uthng thanks for opening this issue.
