### ISSUE TITLE
Cannot exclude submodules when running azure compute module in Terraform

### ISSUE THREAD

**Issue by ngeegoh** [Azure/terraform-azurerm-compute#106]
Hi, 

In my Terraform file, I used azure compute module with the goal of creating just 1 Windows VM connected to my existing virtual network without a public ip attached. However, every time I ran Terraform validate or plan, it kept throwing error saying that I missed out some required fields for public ip and Linux server. When I checked the module description in Terraform module registry, I found out that azure compute module has some submodules which I cant find a way to exclude some of these submodules and even though the readme asking me to remove some of the optional field in the example, it just didnt work. Is this a bug in the module that submodules cannot be excluded, that's why everytime I run the module, it tries to create both resources: linux and windows. 

```terraform 
terraform {
  backend "azurerm" {
    storage_account_name = "__terraformstorageaccount__"
    container_name     = "terraform3"
    key                = "dev.__prefix__.terraform.tfstate"
    access_key           = "__storagekey__"
  }
}
locals {
  virtual_machine_name = "__prefix__-vm"
}

data "azurerm_virtual_network" "virtualnetwork" {
  name                = "vnett1"
  resource_group_name = "Networking"
}

data "azurerm_subnet" "internal" {
  name                 = "Development"
  virtual_network_name = "vnett1"
  resource_group_name  = "Networking"
}

module "compute" {
  source              = "Azure/compute/azurerm"
  version             = "1.2.1"
  vm_hostname         = "${local.virtual_machine_name}"
  resource_group_name              = "__terraformstoragerg__"
  location                         = "__location__"
  admin_password                   = "__admin_password__"
  admin_username                   = "__admin_username__"
  vm_os_simple                     = "WindowsServer"
  remote_port                      = "3389"
  nb_instances                     = 1
  vm_os_publisher                  = "MicrosoftWindowsServer"
  vm_os_offer                      = "WindowsServer"
  vm_os_sku                        = "2016-Datacenter"
  vm_size                          = "Standard_DS2_V2"
  vm_os_id                         = "true"
  vnet_subnet_id                   = "${data.azurerm_subnet.internal.id}"
  delete_os_disk_on_termination    = "true"
  storage_account_type             = "Premium_LRS"
  data_disk                        = "true"
  data_disk_size_gb                = "20"
}

```

- Terraform Version: 0.12.2 and 0.11.14

**Comment by yupwei68** [comment]
@ngeegoh If your intention is to create a windows VM, you could use the submodule "windowsservers",please refer the readme example  [Simple Usage](https://github.com/Azure/terraform-azurerm-compute#simple-usage). Remember to delete the linux VM export sentence.
