### ISSUE TITLE
Deprecation of "network_security_group_id"

### ISSUE THREAD

**Issue by neilfifteen** [Azure/terraform-azurerm-compute#113]
Using the network module...
```
module "network" {
    source              = "Azure/network/azurerm"
    version             = "~> 1.1.1"
    location            = "uksouth"
    allow_rdp_traffic   = "true"
    allow_ssh_traffic   = "true"
    resource_group_name = "${var.prefix}rg"
}
```
...creates a warning like...

> Warning: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.

**Comment by danielfears** [comment]
Update: this should be raised under the Azure/network/azurerm module, not the compute module.

**Comment by danielfears** [comment]
I raised a pull request on the network module to address the incorrect example causing your issue.

https://github.com/Azure/terraform-azurerm-network/pull/32

**Comment by yupwei68** [comment]
hi @danielfears, Thanks for your reply. I am going to close this issue. And we could talk in the PR mentioned.
