### ISSUE TITLE
How to create resources in a location different from the location of the input resource_group_name

### ISSUE THREAD

**Issue by stevencmk1** [Azure/terraform-azurerm-compute#125]
This is more a general question than a bug report.  In 3.0.0 the input location is removed.  How can a VM be created in a location different from the location of the input resource_group_name?

- Terraform Version: 0.12.24
- OS Version: Windows 10

**Comment by sdcscripts** [comment]
The location of the resource group can be different to the resources held within it for most ARM resources, including VMs. 

Resource groups are to manage the lifecycle of multiple objects together, and for governance purposes such as applying RBAC and Policy.

**Comment by yupwei68** [comment]
hi @stevencmk1 Thanks for opening this issue. We will enhance it in the next major release.
