### ISSUE TITLE
issue in machine count not valid - fix attached

### ISSUE THREAD

**Issue by Pwd9000-ML** [Azure/terraform-azurerm-compute#126]
- Terraform Version: latest
- OS Version: vs2017-win2016

Bug description: main.tf
resource count for vm-linux, resource count for vm-windows
Using contains "Windows" is not valid, change to "WindowsServer"

issue detected in variable "vm_os_simple" (description incorrect)
description = "Specify UbuntuServer, WindowsServer, RHEL, openSUSE-Leap, CentOS, Debian, CoreOS and SLES to get the latest image version of the specified os.  Do not provide this value if a custom value is used for vm_os_publisher, vm_os_offer, and vm_os_sku."

line 29: count                         = ! contains(list(var.vm_os_simple, var.vm_os_offer), "Windows") && ! var.is_windows_image ? var.nb_instances : 0

line 92: count                         = (var.is_windows_image || contains(list(var.vm_os_simple, var.vm_os_offer), "Windows")) ? var.nb_instances : 0

fix:

1. line 29: count                         = ! contains(list(var.vm_os_simple, var.vm_os_offer), "WindowsServer") && ! var.is_windows_image ? var.nb_instances : 0
2. line 92: count                         = (var.is_windows_image || contains(list(var.vm_os_simple, var.vm_os_offer), "WindowsServer")) ? var.nb_instances : 0

**Comment by yupwei68** [comment]
Hi @Pwd9000-ML Thanks for opening this issue. We might enhance it in the next major release.
