### ISSUE TITLE
Multiple issues on using Advanced Usage example

### ISSUE THREAD

**Issue by sdcscripts** [Azure/terraform-azurerm-compute#128]
- Terraform Version: Latest
- OS Version: Win10

Bug description:

When trying to run the full Advanced Usage Block there are a few issues. 

1. The network module call doesn't allow for these two options as they don't exist within module: 

```hcl 
allow_rdp_traffic   = true
allow_ssh_traffic   = true 
```
2. The network module call needs to have the subnet names listed when you specify more than one subnet, otherwise it errors. 

Add: 

```hcl 

subnet_names        = ["subnet1", "subnet2"]
```

3. I haven't figured what wrong to cause this but I'm finding during the end of the Linux VM creation I get this returned: 

![image](https://user-images.githubusercontent.com/17180046/78286026-ad935400-7518-11ea-9bf7-242f4674e9a2.png)

It seems like it's related to the SSH key or the settings around one of the blocks in the config, happy to share more info on that. I've tried to remove the SSH key block and go with username\password only but same issue. 

Steps to reproduce: 

1. Run the advanced usage code as per readme.md

**Comment by shubhisethi** [comment]
I am facing the same issue, but when I am running "Advanced Usage example" in azure CLI, it's working...

**Comment by yupwei68** [comment]
hi @sdcscripts , thanks for opening this issue. I have updated the README about two weeks ago. I have tested the advanced usage code in README this morning and it works. Would you like to try the updated code in README? As for ssh-key, you might need to generate ssh-key before running the example by `ssh-keygen -q -t rsa -b 4096 -f $HOME/.ssh/id_rsa`

**Comment by aricbernard** [comment]
@yupwei68, 

For item 1. in the original post:
> The network module call doesn't allow for these two options as they don't exist within module:
> allow_rdp_traffic   = true
> allow_ssh_traffic   = true 
I see no changes in the README to reflect the fact that these inputs are **not valid** for the module Azure/network/azurerm.

**Comment by yupwei68** [comment]
Hi @aricbernard ,thanks for that. I'll fix the README Simple Usage in the next release.
