### ISSUE TITLE
Public IP, domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens

### ISSUE THREAD

**Issue by sbugalski** [Azure/terraform-azurerm-compute#131]
- Terraform Version:
Terraform v0.12.24
provider.azurerm v2.6.0

- OS Version: 
WSL Pengwin 11 (bullseye)

Bug description:
When Creating VM with Public IP without setting _public_ip_dns_ variable it gives following error `Error: domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter and end only with a number or letter`.
It also fails even when _nb_public_ip_ is set to 0.

Steps to reproduce:
1. 
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

module "linuxservers" {
  source  = "Azure/compute/azurerm"
  version = "3.1.0"

  resource_group_name = azurerm_resource_group.example.name

  vm_hostname                   = "vm"
  vm_size                       = "Standard_B1ls"
  nb_instances = 1

  vm_os_publisher               = "Canonical"
  vm_os_offer                   = "UbuntuServer"
  vm_os_sku                     = "18.04-LTS"

  vnet_subnet_id                = module.network.vnet_subnets[0]
  nb_public_ip                  = "1"
  #public_ip_dns                 = ["ipname"]
}

module "network" {
  source              = "Azure/network/azurerm"
  version             = "3.0.1"
  resource_group_name = azurerm_resource_group.example.name
  allow_rdp_traffic   = "true"
  allow_ssh_traffic   = "true"
  subnet_prefixes     = ["10.0.1.0/24"]
}
```

**Comment by sbugalski** [comment]
Made an PR: https://github.com/Azure/terraform-azurerm-compute/pull/132

**Comment by yupwei68** [comment]
hi @sbugalski Thanks for opening this issue and the corresponding PR. Only one minor difference is that I have tested successfully when `nb_public_ip` is set to 0. The PR has been merged. Thanks for your contribution.
