### ISSUE TITLE
Issue while registering azurerm 2.0.0;An argument named "location" is not expected here.

### ISSUE THREAD

**Issue by pnarmeta** [Azure/terraform-azurerm-compute#133]
I'm running in to below issue while registring the module
Error:
 Unsupported argument
  on main.tf line 3, in module "linuxservers":
   3:     location            = "West US 2"
An argument named "location" is not expected here.

Steps to reproduce:

trying to register below modules.
module "linuxservers" {
    source              = "Azure/compute/azurerm"
    location            = "West US 2"
    vm_os_simple        = "UbuntuServer"
    public_ip_dns       = ["linsimplevmips"] // change to a unique name per datacenter region
    vnet_subnet_id      = "${module.network.vnet_subnets[0]}"
  }

**Comment by yupwei68** [comment]
Hi @pnarmeta , thanks for opening this issue. There is an issue that I have forcefully let the VMs be the same location with the resource group provided. I'll fix it in the next release
