### ISSUE TITLE
Where are the resources for the modules?  The sources?

### ISSUE THREAD

**Issue by i255d** [Azure/terraform-azurerm-compute#134]
- Terraform Version: 12.25
- OS Version: 10

Bug description:  The example use this line for source: 'source              = "Azure/vm/azurerm"'
Where are these sources?  Are they somewhere they can be downloaded?

**Comment by yupwei68** [comment]
Hi @i255d , thanks for opening this issue. May I ask where is the example and which line is it?

**Comment by i255d** [comment]
`module "windowsservers" {
  source              = "Azure/compute/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  is_windows_image    = true
  vm_hostname         = "mywinvm" // line can be removed if only one VM module per resource group
  admin_password      = "ComplxP@ssw0rd!"
  vm_os_simple        = "WindowsServer"
  public_ip_dns       = ["winsimplevmips"] // change to a unique name per datacenter region
  vnet_subnet_id      = module.network.vnet_subnets[0]
}`

Line 2?  Is this just an example?

**Comment by yupwei68** [comment]
Hi @i255d , if you create code like
```
module "windowsservers" {
  source              = "Azure/compute/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  is_windows_image    = true
  vm_hostname         = "mywinvm" // line can be removed if only one VM module per resource group
  admin_password      = "ComplxP@ssw0rd!"
  vm_os_simple        = "WindowsServer"
  public_ip_dns       = ["winsimplevmips"] // change to a unique name per datacenter region
  vnet_subnet_id      = module.network.vnet_subnets[0]
}
```
and then you run `terraform init`. It'll automatically download this public module into local.  With `source = "Azure/compute/azurerm"`, it'll know which public module to download.

And right, this is an example how to use this module.

**Comment by i255d** [comment]
Does it say anywhere that source  = "Azure/compute/azurerm" will know to pull the resource from the cloud?
