### ISSUE TITLE
Priority 100 allow_remote_22_in_all

### ISSUE THREAD

**Issue by GarethOates** [Azure/terraform-azurerm-compute#138]
Bug description:
When creating a virtual machine using username and password, there is a network security rule created for the VM, called allow_remote_22_in_all.  This rule is very insecure and allows any machine on the internet the ability to attempt to connect to the machine.  Ideally I would like to limit access to this VM by ip address, but due to the priority of the rule being 100, I am unable to create a rule with a lower priority which can overwrite this.

Is it possible to make the priority of this rule configurable, or to allow an array of ip ranges to be passed in, which can be used as the allowed sources for this rule, instead of it being open to everyone?

Steps to reproduce:

1. Create a VM using username/password instead of ssh_key authentication.

**Comment by GarethOates** [comment]
This looks like it will mostly be solved by #137.  However I would like to see the priority of the rule also being configurable if possible, to add more flexibility this way as well.

**Comment by yupwei68** [comment]
Hi @GarethOates , thanks for opening this issue. I'll close this issue for it has been solved by https://github.com/Azure/terraform-azurerm-compute/pull/137
