### ISSUE TITLE
Do not create Network Security Group when remote_port is not specified

### ISSUE THREAD

**Issue by sheid1309** [Azure/terraform-azurerm-compute#141]
Hello,

Currently, I am using azurerm-compute combine with azurerm-network-security-group. When a VM is created using azurerm-compute, it will automatically create a NIC NSG which blocks all incoming traffic. So my NSG and rules created by using azurerm-network-security-group will not work anymore because it will be applied to the subnet of the VM. 

So I request the feature that azurerm-compute will not create NSG if remote_port is not specified.

Regards,
Anh Quach

**Comment by yupwei68** [comment]
Hi @sheid1309 , thanks for opening this issue. The default NSG rule for the NSG will allow a specific source address to login the vm by some specific ports. The new feature to restrict the source address and override the default NSG rule is released in 3.5.0. You could add a new rule to allow all access by set a new NSG rule with priority `100` to override the default NSG rule with priority `101`.
