### ISSUE TITLE
empty public_ip_address

### ISSUE THREAD

**Issue by regg00** [Azure/terraform-azurerm-compute#149]
- Terraform Version: v0.13.4
- OS Version: Windows 10 Pro 2004

Bug description: Seems that the compute module always return an empty public ip address from it's output when creating a new linux VM. From Terraform documentation, it seems that Azure does not assign an IP address until the VM is started, but I would make sense that the module "knows" about this and pull the IP after the VM is started.

Steps to reproduce:

1. Create VM resource with:
```
module "linuxservers" {
  source              = "Azure/compute/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  vm_os_simple        = "UbuntuServer"
  vnet_subnet_id      = module.network.vnet_subnets[0]
  ssh_key             = "./ssh/id_rsa.pub"
  depends_on          = [azurerm_resource_group.example]
  vm_hostname         = "vm-test-terraform"
  vm_size             = "Standard_B1ls"
  remote_port         = "22"
}
```
2. Create an output based on the module public_ip_address output. 
```
output "linux_vm_public_name" {
  value = module.linuxservers.public_ip_address
}
```
3. Look at output. Value is always empty.

Thanks

**Comment by AliAllomani** [comment]
@regg00 maybe using `allocation_method="Static"` would be helpful in such case.

**Comment by regg00** [comment]
I worked around this issue by creating a custom module based on this one.
In the main.tf file of the new module, I simply added a data source to get the public IP after the creation of the VM like this:

```
data "azurerm_public_ip" "vm" {
  count               = var.nb_instances
  name                = azurerm_public_ip.vm[count.index].name
  resource_group_name = data.azurerm_resource_group.vm.name
  depends_on          = [azurerm_virtual_machine.vm]
}
```

Would be nice for this to be enabled by default if allocation_method is dynamic.
