### ISSUE TITLE
Need the ability to reuse ssh key pair in Azure subscription 

### ISSUE THREAD

**Issue by ramramhariram** [Azure/terraform-azurerm-compute#153]
Currently it appears that when creating a non-windows VM resource, the only option for providing SSH key pair is in the user's local directory. This assumes that the user will their TF code locally which is not always the case (TF cloud being a great alternative). Having the ability instead to  use/reuse SSH key pairs that are created in the Azure portal for a subscription is a much better alternative. This is generally the recommended and default for many other TF providers. 

![Screen Shot 2020-11-18 at 4 30 46 PM](https://user-images.githubusercontent.com/56744845/99607998-e3ab1880-29c1-11eb-9c0c-54a09e5f5c4e.png)

Attached screenshot is the error i got when trying to create an Azure compute resource currently via TF cloud. If the SSH keys were in the subscription and if we had a resource to call it, it will solve this problem.

**Comment by yupwei68** [comment]
Hi @ramramhariram , thanks for opening this issue.
We may enhance this feature in the future. But currently I could not give a plan for it. 
You're welcome to contribute to this module by raising a PR as well. 
If you want to open a PR, please add this feature into the test in test/fixture to integrate the test CI and add this feature in example in README.

**Comment by AliAllomani** [comment]
created PR #159 to add the ability of passing the keys as strings in addition to paths to the module.

to be able to use this feature with azure pre-defined ssh keys, we need a data source to read the keys from azure, as per current azure provider version i don't see any data source to do so.
