### ISSUE TITLE
Question: Default behavior for linux VM without identity definition block

### ISSUE THREAD

**Issue by kgorskowski** [Azure/terraform-azurerm-compute#155]
Hey there! I don't really have a bug or request, just a question regarding a "problem" I am dealing with. Maybe you have some insights into that. We are building Azure Linux infrastructure with terraform on pipelines. We developed our own module and did omit the "identity" block in the first iteration as it was not a requirement. But since a few days ago we can see newly created VMs with no identity block in terraform have  a system assigned identity attached. The next terraform apply is then trying to set the setting to `nul`. Luckily this fails "gracefully" without changing the instance or breaking the terraform operation. But it is kinda strange as older VMs do not have system assigned identities. Are you aware if maybe a default has changed on azure side somewhere? Or do we need to configure the identity block differently? I was trying to implement you dynamic block according to your main.tf. 
If you have any information that could be very helpful. Thanks in advance!

**Comment by yupwei68** [comment]
Hi @kgorskowski , thanks for opening this issue. If you're using `azurerm_linux_virtual_machine`, according to the tf, `identity` is not set by default. If you can reproduce this error, please raise an issue in  https://github.com/terraform-providers/terraform-provider-azurerm/issues

**Comment by yupwei68** [comment]
Sorry that I have to close this issue temporarily. Please reopen it when anything unclear.
