### ISSUE TITLE
Custom_data no longer works

### ISSUE THREAD

**Issue by generalconsensus** [Azure/terraform-azurerm-compute#167]
- Terraform Version: 0.14.7
- OS Version: Mac OSX 11.2.3

Bug description:
Creating a terraform compute machine using this module with the custom_data variable results in the virtual machine not containing any user data
Steps to reproduce:

1. Create a basic Ubuntu 18.04 vm
2. Add simple user data and base64encode it
3. Apply and validate the userdata in Azure and on the machine

**Comment by yupwei68** [comment]
Hi, thanks for opening this issue.
According to [the resource definition](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine), Terraform will base64 encode the custom data, I think you don't need to base64 encode the custom data. 
If the problem still exist, please provide your script, and you reproducing steps, the results and your expected results.

**Comment by lonegunmanb** [comment]
I'm closing this issue since no response from the user.
