### ISSUE TITLE
Deprecated list method

### ISSUE THREAD

**Issue by stgrace** [Azure/terraform-azurerm-compute#169]
- Terraform Version: 0.15.0
- OS Version: macOS Big Sur Version 11.2.3 (20D91)

Bug description:

Deprecated list method is not available anymore in Terraform >= 0.15.0. Should be replaced with `tolist` method:

```bash
│ Error: Error in function call
│ 
│   on .terraform/modules/vm_set/main.tf line 33, in resource "azurerm_virtual_machine" "vm-linux":
│   33:   count                         = ! contains(list(var.vm_os_simple, var.vm_os_offer), "WindowsServer") && ! var.is_windows_image ? var.nb_instances : 0
│     ├────────────────
│     │ var.vm_os_offer is a string, known only after apply
│     │ var.vm_os_simple is a string, known only after apply
│ 
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
```

PR available here: https://github.com/Azure/terraform-azurerm-compute/pull/168

Steps to reproduce:

1.  Use this module with Terraform >= 0.15.0

**Comment by yupwei68** [comment]
Close for https://github.com/Azure/terraform-azurerm-compute/pull/168
