### ISSUE TITLE
Remove unused variable `storage_os_disk_size_gb`

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/terraform-azurerm-compute#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`var.storage_os_disk_size_gb` is an unused variable so we should remove it, but removing an exist variable is a breaking change, so we should leave it to a major upgrade.

### New or Affected Resource(s)/Data Source(s)

`var.storage_os_disk_size_gb`

**Comment by yatzek** [comment]
Os disk size customisation was removed by https://github.com/Azure/terraform-azurerm-compute/pull/189 I am guessing it was done by mistake?


![image](https://user-images.githubusercontent.com/82675711/203758952-4f165075-0071-461b-9e7e-e6331c6fa03b.png)

![image](https://user-images.githubusercontent.com/82675711/203759424-c6a604dc-d7ad-4f4f-ba8d-00260bfd46ea.png)

**Comment by lonegunmanb** [comment]
Thanks @yatzek , you've saved my day.

I've added a version upgrade test, a breaking change detect for variables and outputs, but still I've missed such breaking change. I'll compose a new pr to fix it, and re-check current version.

**Comment by lonegunmanb** [comment]
I've re-check the commit, the only missing parts introduced by #189 is `storage_os_disk_size_gb`, so I'll submit a new pr to fix it. Again, thanks @yatzek for hit this point.
