### ISSUE TITLE
"path" parameter in main.tf file is causing error while running `terraform plan`

### ISSUE THREAD

**Issue by verma-kunal** [Azure/terraform-azurerm-compute#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3.5

### Module Version

4.0.0

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.33.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# Creating a resource_group for azure:
resource "azurerm_resource_group" "tf_azure_provider" {
  name     = "tf_azure_provider"
  location = "East US"
}

module "linuxservers" {
  source              = "Azure/compute/azurerm"
  resource_group_name = azurerm_resource_group.tf_azure_provider.name
  vm_os_simple        = "UbuntuServer"
  public_ip_dns       = ["linsimplevmips"] // change to a unique name per datacenter region
  vnet_subnet_id      = module.network.vnet_subnets[0]
  vm_size             = "Standard_B1ls"

  depends_on = [azurerm_resource_group.tf_azure_provider]
}

module "network" {
  source              = "Azure/network/azurerm"
  resource_group_name = azurerm_resource_group.tf_azure_provider.name
  subnet_prefixes     = ["10.0.1.0/24"]
  subnet_names        = ["subnet1"]

  depends_on = [azurerm_resource_group.tf_azure_provider]
}
```

### tfvars variables values

```hcl
None
```

### Debug Output/Panic Output

```shell
https://gist.github.com/verma-kunal/b4e9e3ba688c010cd28cd0b2f33774e7
```

### Expected Behaviour

Here is a detailed screen recording to the error being reproduced & work around for that
https://drive.google.com/file/d/1AX6q8O9DPj8Aqh5rtrbEHh3ZiA-Y7gbh/view?usp=sharing

### Steps to Reproduce

- just using `terraform plan` would reproduce the error shown above
- Here is the line number from where the error is arising: https://github.com/Azure/terraform-azurerm-compute/blob/4.0.0/main.tf#L109

**Comment by lonegunmanb** [comment]
Hello @verma-kunal, thanks for opening this issue and providing us such detailed error message. It looks like you didn't assign value for `var.ssh_keys` right? This module will use `~/.ssh/id_rsa.pub` as public key if you haven't set any ssh key explicitly, and it looks like this path is absent on your machine. Would you mind checking the example code and set a public key explicitly to see if it could fix your issue?

**Comment by pawelbielatseerene** [comment]
Without having any local id_rsa.pub file I set `ssh_key_values = [ "ssh-rsa FOO..."]` but also got:

```
│ Error: Invalid function argument
│ 
│   on .terraform/modules/vm_gitlab/main.tf line 106, in resource "azurerm_virtual_machine" "vm_linux":
│  106:         key_data = file(ssh_keys.value)
│     ├────────────────
│     │ ssh_keys.value is "~/.ssh/id_rsa.pub"

```

**Comment by lonegunmanb** [comment]
> Without having any local id_rsa.pub file I set `ssh_key_values = [ "ssh-rsa FOO..."]` but also got:
> 
> ```
> │ Error: Invalid function argument
> │ 
> │   on .terraform/modules/vm_gitlab/main.tf line 106, in resource "azurerm_virtual_machine" "vm_linux":
> │  106:         key_data = file(ssh_keys.value)
> │     ├────────────────
> │     │ ssh_keys.value is "~/.ssh/id_rsa.pub"
> ```
> 
> Setting `ssh_key = null` helped.

@pawelbielatseerene yes, since the `var.ssh_key` have a [default value](https://github.com/Azure/terraform-azurerm-compute/blob/master/variables.tf#L222-L226) so if we don't want to use this parameter, we should set it to `null` explicitly.

**Comment by lonegunmanb** [comment]
I'm closing this issue due to no user's response. Please feel free to reopen this issue if you've further question, thanks!
