### ISSUE TITLE
Support for azurerm_virtual_machine_extension should be a set

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-compute#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The newly implemented support for azurerm_virtual_machine_extension only supports a singular extensions.
Typically one would install several, like NetworkWatcherAgentLinux + AADSSHLoginForLinux + AzurePolicyforLinux.
So if the current singular variable could rather become a set this should work

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Potential Terraform Configuration

```hcl
See description
```

**Comment by lonegunmanb** [comment]
Thanks for opening this issue @davidkarlsen, good point! I would like to add a new variable with `set` type meanwhile keeping the current singular variable for backward compatibility.

**Comment by davidkarlsen** [comment]
> azurerm_virtual_machine_extension

SGTM, maybe add a new input var defaulted to `[]` named `azurerm_virtual_machine_extensions`

**Comment by lonegunmanb** [comment]
Hi @davidkarlsen , almost finish my draft but one question raised up, as this [document](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#extension-schema) described:

>Only one version of an extension can be installed on a VM at a point in time. Specifying a custom script twice in the same Azure Resource Manager template for the same VM will fail.

I confirm that the `type` for  `azurerm_virtual_machine_extensions` must be unique for one vm, we cannot create two extensions for one vm with the same `type`. But I'm not sure whether we can create multiple extensions with same `type` and different `publisher`. For now I use `map` as this new added variable's `type`, and map's key is extension's `name`, and I added a validation block to ensure that the `type` for extensions is unique,.

**Comment by davidkarlsen** [comment]
How about using a set(object) ?

**Comment by lonegunmanb** [comment]
The advantage of using `map(object)` as type is, as the key is extension's `name`, you'll get a free name uniqueness check.

On the other hand, if we use `set(object)` as type, then we kept the object's schema as same as the singular version variable.

I think you're right, we should keep the consistency.
