### ISSUE TITLE
Invalid Module variable block

### ISSUE THREAD

**Issue by BMustafa97** [Azure/terraform-azurerm-compute#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.2.6

### Module Version

5.0.0

### AzureRM Provider Version

3.35. 0

### Affected Resource(s)/Data Source(s)

compute vm

### Terraform Configuration Files

```hcl
module "compute" {
  source  = "Azure/compute/azurerm"
  version = "4.2.0"
  # insert the 2 required variables here
  resource_group_name = azurerm_resource_group.az_pro_infra.name
  use_for_each = true
  # other variables
  vm_hostname = "pro-${local.local_environment}-sql-vm"
  is_windows_image    = true
  admin_password      = output.password.result
  vm_os_simple        = "WindowsServer"
  public_ip_dns       = ["winsimplevmips"] // change to a unique name per datacenter region
  vnet_subnet_id      = module.vnet.subnet_ids[0]
}
```

### tfvars variables values

```hcl
nada
```

### Debug Output/Panic Output

```shell
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid type specification
│ 
│   on .terraform/modules/resource_groups.compute/variables.tf line 264, in variable "vm_extension":
│  264:     failure_suppression_enabled = optional(bool, false)
│ 
│ Optional attribute modifier expects only one argument: the attribute type.
```

### Expected Behaviour

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

### Actual Behaviour

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid type specification
│ 
│   on .terraform/modules/resource_groups.compute/variables.tf line 264, in variable "vm_extension":
│  264:     failure_suppression_enabled = optional(bool, false)
│ 
│ Optional attribute modifier expects only one argument: the attribute type.

### Steps to Reproduce

terraform init

### Important Factoids

Looks like the variables file has an issue on:

**Comment by BMustafa97** [comment]
`variable "vm_extension" {
  description = "(Deprecated) This variable has been superseded by the `vm_extensions`. Argument to create `azurerm_virtual_machine_extension` resource, the argument descriptions could be found at [the document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension)."
  type = object({
    name                        = string
    publisher                   = string
    type                        = string
    type_handler_version        = string
    auto_upgrade_minor_version  = optional(bool)
    automatic_upgrade_enabled   = optional(bool)
    failure_suppression_enabled = optional(bool, false)
    settings                    = optional(string)
    protected_settings          = optional(string)
    protected_settings_from_key_vault = optional(object({
      secret_url      = string
      source_vault_id = string
    }))
  })
  default   = null
  sensitive = true # Because `protected_settings` is sensitive
}`

issue being: `failure_suppression_enabled = optional(bool, false)`

**Comment by lonegunmanb** [comment]
Thanks @BMustafa97 for opening this issue, the issue is caused by the Terraform version. The [Optional Object Type Attributes](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#optional-object-type-attributes) was introduced by Terraform 1.3, but this module hasn't upgraded the version restriction yet.

I'll submit a pull request to fix that, meanwhile, a quick fix is upgrading Terraform version to 1.3+ on your side.

**Comment by gabriel-loka** [comment]
@lonegunmanb I upgrade my tf version and still have an issue with that `failure_suppression_enabled = optional(bool, false)`, Do I need to do something else?

Thanks

**Comment by lonegunmanb** [comment]
> @lonegunmanb I upgrade my tf version and still have an issue with that `failure_suppression_enabled = optional(bool, false)`, Do I need to do something else?
> 
> Thanks

@gabriel-loka Would you please share your Terraform version and the error message you've encounter? Thanks!
