### ISSUE TITLE
To specify more than one hostname,admin_password when using *servers module

### ISSUE THREAD

**Issue by praveenc** [Azure/terraform-azurerm-compute#23]
when provisioning multiple servers at once using `nb_instances=2` currently you can only specify a single `admin_password`, which applies for both provisioned VMs, is it possible to make `vm_hostname` and `admin_password` as a `list` as opposed to a `string` - this way we can have more control on the VMs parameters being deployed? also eliminates manual intervention post-deploy.

maybe adding couple more variables with names `vm_hostnames` and `admin_passwords` of type `list` without overriding the existing variable names would help perhaps? - my 2 cents

Btw, thanks for this module - my TF template looks lot leaner now.
Keep up the good work!

**Comment by dtzar** [comment]
Thanks!  Unless I'm missing something - VMs only allow one `admin_password` string (not a list), so this would be impossible.  As for `vm_hostnames`  as a list - this would be tricky to implement with HCL (although likely possible) while keeping the ability for people to keep the current _easy_ hostname capabilities.  I'd argue that for your scenario where you want different hostnames and passwords you might want to actually have different modules for those.  For all those reasons, I'm not inclined to spend time to code the multiple hostname scenario - but I'd entertain a PR ;).

**Comment by dtzar** [comment]
I'll leave it open in case anyone else out there wants to work on this.

**Comment by lonegunmanb** [comment]
Since this module used `count` and according to the [document](https://developer.hashicorp.com/terraform/language/meta-arguments/count#when-to-use-for_each-instead-of-count):

>If your instances are almost identical, count is appropriate. If some of their arguments need distinct values that can't be directly derived from an integer, it's safer to use for_each.

I will create a new module for virtual machine which would use "modern" resource like `azurerm_linux_virtual_machine` and `for_each`, I'd like to introduce this feature in that new module. I'll leave this issue open until I've implemented it in the new module.

**Comment by lonegunmanb** [comment]
I'm closing this issue since we've migrated [new module](https://github.com/Azure/terraform-azurerm-virtual-machine) to Azure organization, any further issue could be raised there. Thanks for your participating folks!
