### ISSUE TITLE
Set the resource_group_name while using compute module

### ISSUE THREAD

**Issue by metacpp** [Azure/terraform-azurerm-compute#25]
In the sample usage code, the compute module uses default resource group, which is not aligned with network module's resource group name.

**Comment by ricoli** [comment]
Shouldn't the creation of a resource group be optional in this module? One would normally want to simply use an existing resource group, such as the one created by the network module for example.

**Comment by dtzar** [comment]
You can also easily align the resource group names when you provision the modules...

**Comment by ricoli** [comment]
One could only use the same resource name in both modules ("align") if the modules are in the same state file, which might not be the case.

**Comment by dtzar** [comment]
Closing this out - resource group should be kept separate out of this module.
