### ISSUE TITLE
Data disk deletion on termination does not work with Windows VMs

### ISSUE THREAD

**Issue by jneilaglez** [Azure/terraform-azurerm-compute#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3.8

### Module Version

5.2.0

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine.vm_windows

### Terraform Configuration Files

```hcl
resource "random_id" "random_id" {
  byte_length = 4
}

module "compute" {
  source  = "Azure/compute/azurerm"
  version = "5.2.0"

  resource_group_name = "rg-invent"

  vm_hostname      = "${random_id.random_id.hex}-w"
  vm_size          = "Standard_B2s"
  vnet_subnet_id   = "/subscriptions/invent/resourceGroups/rg-invent/providers/Microsoft.Network/virtualNetworks/Az-invent/subnets/PoCsCommon"
  location         = "westeurope"
  is_windows_image = true
  admin_username   = "userinvent"
  admin_password   = "passwordinvent-123456"
  vm_os_simple     = "WindowsServer"
  nb_public_ip     = 0
  license_type     = "Windows_Client"

  delete_data_disks_on_termination = true
  delete_os_disk_on_termination    = true
}
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.40.0"
    }
  }
}

provider "azurerm" {
  skip_provider_registration = "true"
  features {}
}
```

### tfvars variables values

```hcl
NA
```

### Debug Output/Panic Output

```shell
# module.compute.azurerm_virtual_machine.vm_windows[0] will be created
  + resource "azurerm_virtual_machine" "vm_windows" {
      + delete_data_disks_on_termination = false
      + delete_os_disk_on_termination    = true
```

### Expected Behaviour

Data disk (on Windows VMs) should be removed when `terraform destroy` is executed because the flag `  delete_data_disks_on_termination` is set to true. 

### Actual Behaviour

Data disk are not remove when the stack is destroyed, they are only unattached.

The `main.tf` file has not the `delete_data_disks_on_termination` variable referenced within the `azurerm_virtual_machine.vm_windows` resource.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by lonegunmanb** [comment]
Hi @jneilaglez, apology for the late reply, I've tested the following config:

```hcl
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

resource "random_id" "random_id" {
  byte_length = 4
}

resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = "computemodule-${random_id.random_id.hex}"
}

resource "azurerm_virtual_network" "vnet" {
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg.location
  name                = "vnet"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  address_prefixes     = ["10.0.0.0/24"]
  name                 = "subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
}

resource "random_password" "password" {
  length = 20
}

module "compute" {
  count = 1

  source  = "Azure/compute/azurerm"
  version = "5.3.0"

  resource_group_name = azurerm_resource_group.rg.name

  vm_hostname      = "${random_id.random_id.hex}-w"
  vm_size          = "Standard_B2s"
  vnet_subnet_id   = azurerm_subnet.subnet.id
  location         = azurerm_resource_group.rg.location
  is_windows_image = true
  admin_username   = "userinvent"
  admin_password   = random_password.password.result
  vm_os_simple     = "WindowsServer"
  nb_public_ip     = 0
  license_type     = "Windows_Client"

  delete_data_disks_on_termination = true
  delete_os_disk_on_termination    = true
}
```

After applying I changed `count` to `0` and apply again, only resource group, virtual network, and subnet remained this time, the os disk was deleted along with the virtual machine.

Would you please give us the steps to reproduce your issue? Thanks!

**Comment by lonegunmanb** [comment]
I'm closing this issue since no response from the user. Please feel free to reopen it when you have an example that could reproduce this issue @jneilaglez .

**Comment by jneilaglez** [comment]
Ey @lonegunmanb sorry for my late too, I am not sure why your code works (I have not test it yet), Have you formatted the data disk? In the new git tag I think you are not setting the `delete_data_disks_on_termination` to the Terraform resource in Windows VM but in Linux

Windows VM resource
https://github.com/Azure/terraform-azurerm-compute/blob/main/main.tf#L209-L211

Linux VM resource
https://github.com/Azure/terraform-azurerm-compute/blob/main/main.tf#L67-L70

I created a fork and "fix" the bug in a feature branch to test it, you can review it. Let me a few days to test your code, maybe I can start a simple PR with this same changes:

https://github.com/jneilaglez/terraform-azurerm-compute/commit/bc880715d92386ab2aae74ae81b05adb3b8a6703#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR193
