### ISSUE TITLE
Shall we hide the provision of network into compute module ?

### ISSUE THREAD

**Issue by metacpp** [Azure/terraform-azurerm-compute#26]
The story is I planed to provision a Linux VM with SSH tunnel enabled. From compute module's input arguments, I only found ssh_key field then I set it to my local public key to provision it. When I tried to access it through ssh, it was not working. I did some troubleshooting and finally realize that I need to set "allow_ssh_traffic" field to be true in the network module. Then my suggestion is: if the network module is always necessary here to provision a simple VM, why we don't put it into the module definition ? Or at least, we can put some notice in the README for ssh_key field.

**Comment by dcaro** [comment]
@metacpp when we created the module, we have decided to keep the network module separate in order to allow someone to use the compute module either with an existing network or to provision the vnet separately.
We may need to update the documentation if this is not clear.

**Comment by metacpp** [comment]
@dcaro let's update the documentation at section of ssh_key.

**Comment by ricoli** [comment]
Perhaps make that part that is creating the security group in the network module to be optional? To be honest I believe security groups should have their own module, the same that AWS has done it: https://registry.terraform.io/modules/terraform-aws-modules/security-group/aws/1.5.0

**Comment by rberlind** [comment]
I think documenting the fact that SSH to the instance is only possible if allow_ssh_trafic = true for the network module is very important.  It took me a long time to figure that out and I only figured it out when I finally read this issue.  I had not read it initially because the subject/title did not seem relevant to my problem.

**Comment by noelbundick** [comment]
Got bit by this today also. Was rough on me, as a Terraform newbie, that the basic example didn't work without an undocumented variable being set - especially when the docs lead you to believe that you are, in fact, opening port 22 for SSH. 

Would be nice to have the subnet NSG be opt-in w/ configuration, or as suggested - to split NSG's from the network module

**Comment by dtzar** [comment]
I updated the examples to allow SSH/RDP access by default, so closing this out.
