### ISSUE TITLE
public_ip_address output gives error

### ISSUE THREAD

**Issue by rberlind** [Azure/terraform-azurerm-compute#34]
The public_ip_dns_name output gives error: 

Error: Error applying plan:

2 error(s) occurred:

* module.windowsserver.output.public_ip_address: Resource 'azurerm_public_ip.vm' does not have attribute 'ip_address' for variable 'azurerm_public_ip.vm.*.ip_address'
* module.linuxserver.output.public_ip_address: Resource 'azurerm_public_ip.vm' does not have attribute 'ip_address' for variable 'azurerm_public_ip.vm.*.ip_address'

This is running main.tf very similar to that in https://github.com/Azure/terraform-azurerm-compute#simple-usage.

The VMs are actually created despite the error.

I suspect the problem is that the values of ${azurerm_public_ip.vm.*.ip_address} are not yet assigned when the outputs are evaluated.  Note that the [documentation](https://www.terraform.io/docs/providers/azurerm/r/public_ip.html) for the azurerm_public_ip resource does have a warning saying that dynamic public IP addresses are not allocated until they are assigned to a resource.

It might help to add an azurerm_public_ip data source that would read back the public IP from the resource. See the example of doing this after creating a new VM [here](https://www.terraform.io/docs/providers/azurerm/d/public_ip.html#example-usage-retrieve-the-dynamic-public-ip-of-a-new-vm-). If doing that my itself did not do the trick, we could potentially add a null_resource with a 30 second sleep before the new data source.

**Comment by dtzar** [comment]
Yes, this is just a timing problem with the outputs.  The outputs are just there for convenience.  When I've had this happen and ran `terraform apply` immediately after the 1st time, the outputs work fine.

**Comment by rberlind** [comment]
It also seems to depend on version of Terraform used.  I had been using with 0.11.1.  But I just ran with 0.10.8 and did not see any errors on the first apply.

I also see what you said about second terraform apply then successfully giving the outputs. When I have some time (hopefully later this week), I will test my proposal to use an azurerm_public_ip data source that would read back the public IP from the resource possibly after a null_resource with local-exec provisioner that does a 30 second sleep. If that works, I will submit a pull request.

**Comment by asote** [comment]
Still getting this error:

module.windowsserver.output.public_ip_address: Resource 'azurerm_public_ip.vm' does not have attribute 'ip_address' for variable 'azurerm_public_ip.vm.*.ip_address'

**Comment by rberlind** [comment]
I believe you can avoid the error by setting environment variable TF_WARN_OUTPUT_ERRORS=1.  This was added in Terraform 0.11.1 and referenced by https://github.com/hashicorp/terraform/blob/v0.11.2/CHANGELOG.md#0111-november-30-2017.

**Comment by asote** [comment]
Thanks. That worked!

**Comment by herasimau** [comment]
Hello, i don't have any error, but public_ip_address output gives  me an ID of VM instead of public ip.
Can you check it please ? 
Thank you.

**Comment by cd83** [comment]
Ran into this again today. 

While a timing issue certainly exists (does not return data on same run but on following runs), there is still an error where `data.azurermpublicip` successfully returns `idle_timeout_in_minutes` and `tags`, but not `domain_name_labels, fqdn, ip_address`

Code to get idle_timeout_in_minutes and tags:

```
resource "azurerm_public_ip" "myVMpubIP" {
  name                         = "myVMpubIP"
  location                     = "westus"
  resource_group_name          = "terraformRG"
  public_ip_address_allocation = "Dynamic"
  idle_timeout_in_minutes      = 30
  depends_on                   = ["azurerm_virtual_machine.myterraformvm"]

  tags {
    environment = "test"
  }
}

data "azurerm_public_ip" "myVMpubIPdata" {
  name                = "myVMpubIP"
  resource_group_name = "terraformRG"
}

output "myVM_idle_timeout_in_minutes" {
  value = "${data.azurerm_public_ip.myVMpubIPdata.idle_timeout_in_minutes}"
}

output "myVM_tags" {
  value = "${data.azurerm_public_ip.myVMpubIPdata.tags}"
}
```

returns:

```
myVM_idle_timeout_in_minutes = 30
myVM_tags = {
  environment = test
}
```

However, attempting to get `domain_name_labels`, `fqdn`, or `ip_address`:

```
output "myVM_fqdn" {
  value = "${data.azurerm_public_ip.myVMpubIPdata.fqdn}"
}


output "myVM_ip_address" {
  value = "${data.azurerm_public_ip.myVMpubIPdata.ip_address}"
}


output "myVM_domain_name_label" {
  value = "${data.azurerm_public_ip.myVMpubIPdata.domain_name_label}"
}
```

returns:

```
* output.myVM_fqdn: Resource 'data.azurerm_public_ip.myVMpubIPdata' does not have attribute 'fqdn' for variable 'data.azurerm_public_ip.myVMpubIPdata.fqdn'
* output.myVM_ip_address: Resource 'data.azurerm_public_ip.myVMpubIPdata' does not have attribute 'ip_address' for variable 'data.azurerm_public_ip.myVMpubIPdata.ip_address'
* output.myVM_domain_name_label: Resource 'data.azurerm_public_ip.myVMpubIPdata' does not have attribute 'domain_name_label' for variable 'data.azurerm_public_ip.myVMpubIPdata.domain_name_label'
```

**Comment by rberlind** [comment]
That's fine.  But the outputs of the module cause errors regardless because of the change made in Terraform 0.11.  And the workaround of setting TF_WARN_OUTPUT_ERRORS=1 will go away in Terraform 0.12.

**Comment by yupwei68** [comment]
HI @rberlind , thanks for opening this issue. Currently, in the release v3.0.0, this bug could not be reproduced. And I'd like to close this issue.

**Comment by rberlind** [comment]
OK

**Comment by jmspring** [comment]
I'm seeing this same bug persist in the azurerm 2.6.0 provider.  I specifically have azurerm_public_ip defined with `sku` as `Standard` and `allocation_method` as `Static`.

Setting this variable TF_WARN_OUTPUT_ERRORS=1` gets rid of the error but the outputs don't show up even on a second apply.

@dtzar, @yupwei68 - any thoughts?
