### ISSUE TITLE
Multiple "linuxservers" blocks

### ISSUE THREAD

**Issue by horsey** [Azure/terraform-azurerm-compute#37]
I need to deploy multiple types of "linuxservers" - basically "linuxservers" of different configuration on different subnets. 

I get an error saying:
```Error: Failed to load root config module: Error loading modules: module linuxservers: duplicated. module names must be unique```

Is there a way to deploy several classes of "linuxservers" on different subnets?

**Comment by dtzar** [comment]
Yes, you would just use different module names for the different types.
