### ISSUE TITLE
Bumping up azurerm version

### ISSUE THREAD

**Issue by horsey** [Azure/terraform-azurerm-compute#39]
Hello, 
Is it possible to bump up the version of azurerm to the latest version: v1.0.0?  I ask because the latest version of azurerm provider has a few fixes that are required for the proper working of terraform in a few use cases. 

Please refer to: 
https://github.com/hashicorp/terraform/issues/17053

**Comment by m4h3** [comment]
this makes this module unusable atm. Please do the version bump as we can't have multiple versions of the same provider https://github.com/hashicorp/terraform/issues/16641.

**Comment by dtzar** [comment]
We have this on our backlog to complete.

**Comment by straubt1** [comment]
Any movement on this? The latest Azure Provider is at 1.6 and this module is version locked at 0.3.
