### ISSUE TITLE
os_profile_windows_config must be specified

### ISSUE THREAD

**Issue by Phydeauxman** [Azure/terraform-azurerm-compute#44]
New to Terraform and trying to use the "Azure/compute/azurerm" module to deploy a vm.  Getting the error below:

```
azurerm_virtual_machine.vm-windows: Error: either a os_profile_linux_config or a os_profile_windows_config must be specified
```

Below is my tf file

```
module "vm" {
  source  = "Azure/compute/azurerm"
  version = "1.0.2"

  location = "${var.location}"
  vnet_subnet_id = "${module.network.vnet_subnets[0]}"

  resource_group_name = "${var.resource_group}"
  vm_hostname = "${var.vm1_name}"
  admin_username = "${var.adm_account}"
  admin_password = "${var.adm_password}"
  vm_size = "Standard_B2s"
  storage_account_type = "Standard_LRS"
  vm_os_offer = "WindowsServer"
  vm_os_publisher = "MicrosoftWindowsServer"
  vm_os_sku = "2016-Datacenter"
  public_ip_dns = "${var.vm1_name}"
  remote_port = "3389"
}

output "vm_public_name" {
    value = "${module.vm.public_ip_dns_name}"
  }

  output "vm_public_ip" {
    value = "${module.vm.public_ip_address}"
  }

  output "vm_private_ips" {
    value = "${module.vm.network_interface_private_ip}"
  }
```

**Comment by horsey** [comment]
@Phydeauxman 
You should probably check whether your variables

```vm_os_offer```, ```vm_os_publisher``` and ```vm_os_sku``` are valid strings that is understood by Azure.

**Comment by Phydeauxman** [comment]
They are all valid values.  Used them in a template where I was defining all resources explicitly in the template and it worked as expected.

**Comment by dtzar** [comment]
We just made a push (v1.1.5) which likely fixes you issue @Phydeauxman.  Could you please check?

**Comment by riccardin** [comment]
Was this issue ever resolved? I'm getting the same error. I'm using next versions:

* provider.azurerm: version = "1.12"
* terraform 0.11.7

**Comment by DKresselBD** [comment]
add this to the VM block:
    os_profile_windows_config {
    provision_vm_agent = true
  }

**Comment by yupwei68** [comment]
Hi @Phydeauxman , thanks for opening this issue. I have test the code in the recent release v3.0.0. This bug can not be reproduced. Except that, in your code, `is_windows_image = true ` should be added. And `public_ip_dns` need to be assigned with a list of string
