### ISSUE TITLE
Differentiating VM hostnames  in AV set

### ISSUE THREAD

**Issue by horsey** [Azure/terraform-azurerm-compute#45]
Hello, 
When I am deploying more than 1 VM using the ```terraform-azurerm-compute``` module, I find that all my hostnames are named the same. 

Is there a way I can name the hostnames based on the pattern: hostname with an incrementing number suffixed ? For ex, if my vm name is ```appserver```, can I name them as ```appserver0``` and ```appserver1``` ?

**Comment by horsey** [comment]
I see that https://github.com/Azure/terraform-azurerm-compute/issues/23 is a very similar issue, but any update on this?
Is it still open to fix?

**Comment by dtzar** [comment]
23 is asking for a custom list to define these values which is a lot of work for little return, so no plans on our side to implement this.

However - your ask to have the vms named differently incrementing by count is very understandable.  This would be easy to fix by simply replacing ` computer_name  = "${var.vm_hostname}"` with `    computer_name  = "${var.vm_hostname}${count.index}" everywhere in `main.tf`.  PR welcome :).
