### ISSUE TITLE
security groups in a separate module

### ISSUE THREAD

**Issue by ricoli** [Azure/terraform-azurerm-compute#47]
Following the discussion in https://github.com/Azure/terraform-azurerm-network/issues/5, the suggestion is to let users decide what to do in terms of security groups, instead of having security groups forced into the users as part of using the compute module. Having a separate terraform module to do operations related to security groups would be a great improvement in my opinion, and it's now in the backlog, as per https://github.com/Azure/terraform-azurerm-network/issues/5#issuecomment-359011275. This would also serve the separation of concerns principle.

**Comment by yupwei68** [comment]
Hi @ricoli , thanks for opening this issue. In recent releases, we have separate the creation of nsg rules from nsg. You could add your custom nsg rules into this module. And I'd like to close this issue temporarily.
