### ISSUE TITLE
image from the marketplace require plan parameter

### ISSUE THREAD

**Issue by vvish5** [Azure/terraform-azurerm-compute#48]
This is module doesn't support when we specifies the name of the image from the marketplace like center-for-internet-security-inc, as it require plan parameter 

Plan supports the following:
name - (Required) Specifies the name of the image from the marketplace.
publisher - (Required) Specifies the publisher of the image.
product - (Required) Specifies the product of the image from the marketplace.

below is the link for reference 

https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html

**Comment by dopsy** [comment]
any update? We are having same issue

**Comment by JunyiYi** [comment]
Hi @vvish5 @dopsy , this is an enhancement to enable the marketplace feature for this module. It is not on our schedule right now, but we really welcome your contributions. Thanks.
