### ISSUE TITLE
tags in resource group can cause conflict 

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-compute#54]
The resource group definition includes a tags map, this causes a conflict if you're deploying into an existing resource group which needs to be tagged differently, which is my use case.

I notice that terrform-azurerm-vnet module does not include tags for the resource group resource, that would be my preference, unless the wisdom of the many can point to a way where I can avoid this conflict.

Happy to submit a PR against this if helpful.

**Comment by kewalaka** [comment]
thinking about this some more - I think what would be better is if there was a 'use existing' flag.  If that is true, then the data provider could be used to get the details of the resource group, otherwise it would be created.

if the tag if removed altogether as I initially thought that would break the use case where someone actually wants the VM in a dedicated resource group and wants that tagged.

playing around with this at the moment but don't have anything to share just yet.

**Comment by yupwei68** [comment]
HI @kewalaka , thanks for opening this issue. This has been fix in the recent release v3.0.0.
