### ISSUE TITLE
support for the "license_type" parameter

### ISSUE THREAD

**Issue by andrew-best-diaxion** [Azure/terraform-azurerm-compute#59]
The Azure documentation for using your EA license entitles with Azure
are available from https://docs.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing

When using the Azure CLI the command to create a new VM with the HUB option is
documented at https://docs.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create
--license-type Windows_Client|Windows_Server.
The MS documentation isnt very clear though about which value should be used
to enable HUB when creating a VM. A bug has been opened with the docs team about this
https://github.com/Azure/azure-cli/issues/6051

In the mean time, according to https://blogs.msdn.microsoft.com/azureedu/2016/04/13/how-can-i-use-the-hybrid-use-benefit-in-azure/
the correct value to use in PowerShell is Windows_Server

Terraform supports this via the https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#license_type
option. The azurerm_virtual_machine directive has an optional parameter called "license_type". From what I can tell this is supposed to control what Windows license type is used when the VM is created. Customer can license an Azure Windows VM using the PAYG license or their EA entitlements (called Hybrid Use Benefit).

Would be nice to have this supported in the module as it would make it much quicker and easier to create some VMs.

**Comment by CrowderKroger** [comment]
#144
