### ISSUE TITLE
Resource Group Creation Causes Deletion

### ISSUE THREAD

**Issue by rossedman** [Azure/terraform-azurerm-compute#60]
If a resource group previously exists, and you pass it into this module it will manage that group in its state. When you delete this module from your state it will delete the resource group that previously existed. When managing Terraform state in layers this presents a huge problem and actually causes problems with the Azure API where the resource group will stay in a "Deleting" state for long periods of time especially when there are resources in the group that were not managed by this module. This code should be removed:

```
resource "azurerm_resource_group" "vm" {
  name     = "${var.resource_group_name}"
  location = "${var.location}"
  tags     = "${var.tags}"
}
```

This is not best practices with Terraform. The resource group name should be passed in but not managed through the module itself preventing these errors.

**Comment by dcaro** [comment]
@rossedman Thanks for reporting this issue. I will have a look at it later this week.

**Comment by rossedman** [comment]
@dcaro Can make a PR, happening in lots of Azure modules

**Comment by dcaro** [comment]
PR are welcome! Also please note that we are deemphasizing this module and are evolving now this module: https://github.com/Azure/terraform-azurerm-vm.
