### ISSUE TITLE
Resource naming consistency

### ISSUE THREAD

**Issue by mbrancato** [Azure/terraform-azurerm-compute#62]
A number of naming consistency issues exist within the module. In some cases the format is `<resource type>-<cluster base name>-<index>` (publicip, nic, osdisk, datadisk) whereas other components have the format `<cluster base name>-<resource type>` (avset, nsg*). The vm names lacks a dash separator leaving the azure resource name and hostname as `<cluser base name><index>`. Additionally, the NSG is named with a port number of remote access included in the name as `<cluster base name>-<port number>-nsg` which seems very odd.

My suggestion would be to standardize these within the module. There is no real global standard. When using the portal, however, most templates appear to take a base or hostname and append the resource type to the end. Other templates such as those in https://github.com/Azure/azure-quickstart-templates/ append the resource type, but those resource type names vary within the templates (e.g. pub-ip, publicIP).

**Comment by yupwei68** [comment]
Hi @mbrancato , thanks for opening this issue. This has been fix in the recent release v3.0.0.
