### ISSUE TITLE
When Destroying The Module The Resource Group Was Destroyed As Well

### ISSUE THREAD

**Issue by barakAtSoluto** [Azure/terraform-azurerm-compute#64]
Terraform v0.11.3
+ provider.azurerm v1.6.0

main.tf:

```
provider "azurerm" {}

module "windowsservers" {
    source              = "Azure/compute/azurerm"

    resource_group_name = "${var.RG_name}"
    location            = "${var.local}"
    vm_hostname         = "${var.hostname}"
    admin_password      = "${var.passwd}"
    public_ip_dns       = []
    nb_public_ip        = "0"
    remote_port         = "3389"
    nb_instances        = "1"
    vm_os_publisher     = "MicrosoftWindowsServer"
    vm_os_offer         = "WindowsServer"
    vm_os_sku           = "2012-R2-Datacenter"
    vm_size             = "Standard_DS2_V2"
    vnet_subnet_id      = "${var.subnet_id}"
  }
```

Next to main I had a var.tf file with the relevant vars such that every resource referenced was created outside the scope of this project - especially the `resource_group`. 
After provisioning I wanted to destroy the instance but `terraform destroy` in the context of the former main.tf (only representation of resources in the dir) wanted to destroy the RG as well.

Please prevent the provider from destroying resources not created by in current scope.

**Comment by mbrancato** [comment]
This is a bug and captured in #60. Suggest closing this issue.  As a workaround, you can pull the module and edit out the resource group creation in your local usage.

**Comment by JunyiYi** [comment]
Hi @barakAtSoluto , I agree with @mbrancato . Let's track the issue in #60 .
