### ISSUE TITLE
Option to not create a resource group

### ISSUE THREAD

**Issue by smerrell** [Azure/terraform-azurerm-compute#68]
While working with this module I noticed that it [always includes a Resource Group](https://github.com/Azure/terraform-azurerm-compute/blob/627c6c212af8aa4cc1a004e8d35e9770d6f61e0c/main.tf#L14-L18) when using the module. This looks like it can cause problems as #54 #60 and #64 appear to show.

I'd like to propose providing some way to tell the module to not create a Resource Group and instead use one that exists. I've done some work locally but wanted to start a discussion before opening a Pull Request.

Here is what I've done so far with the module.

Added a new variable `create_resource_group` that looks like this:

```hcl
variable "create_resource_group" {
  description = "Whether or not to create a new resource group or reference an existing resource group"
  default     = true
}
```

For the resource group I've added this:

```hcl
resource "azurerm_resource_group" "vm" {
  count    = "${var.create_resource_group}" # creates the group if set to true
  name     = "${var.resource_group_name}"
  location = "${var.location}"
  tags     = "${var.tags}"
}
```

I also had to change anywhere that was referencing `azurerm_resource_group.vm.name` and `azurerm_resource_group.vm.location` to use the variables `resource_group_name` and `location`.

Is this something people would be interested in having? Are there other ways we could approach whether or not we create a resource group or associate the module with an existing resource group? I'd love to get some feedback and see if this is something worth working on. Thanks!

**Comment by JunyiYi** [comment]
This issue is similar to #54 . But let's still using two issues while bumping up the priority.

**Comment by yupwei68** [comment]
Let's discuss in https://github.com/Azure/terraform-azurerm-compute/issues/60. I'm going to close this issue.
