### ISSUE TITLE
Are nics supposed to be added to the NSG?

### ISSUE THREAD

**Issue by korlaxxalrok** [Azure/terraform-azurerm-compute#79]
- Terraform Version: 
```
Terraform v0.11.8
+ provider.azurerm v0.3.3
+ provider.random v1.3.1
```

- OS Version:
```
macOS 10.14
```

Bug description:
The below verbiage suggests that nics are associated to the NSG. Is this the case, or am I misunderstanding what the module does?
>Network Security Group (NSG) created with a single remote access rule which opens var.remote_port port or auto calculated port number if using var.vm_os_simple to all nics

Steps to reproduce:
1. Create and apply plan following basic guidelines in readme.
2. NSGs are created, but nics are not associated.

**Comment by yupwei68** [comment]
HI @korlaxxalrok ,they are associated.
