### ISSUE TITLE
Latest version of the module uses very old version of azurerm plugin

### ISSUE THREAD

**Issue by juanjojulian** [Azure/terraform-azurerm-compute#81]
I'm using latest Terraform and plugin version, tried this in Mac OS X (latest) aswell as Linux with same result.

Please, review code as latest version of main.tf is pointing to azurerm version 0.33 and it breaks all modern code:

Your main.tf:

`provider "azurerm" {
  version = "~> 0.3"
}`

What is happening in my side:

`$ terraform init -backend-config=azure-backend-credentials.auto.tfvars
Initializing modules...
- module.linuxservers
  Found version 1.1.7 of Azure/compute/azurerm on registry.terraform.io
  Getting source "Azure/compute/azurerm"
- module.network
  Getting source "git::ssh://git@XXXX.org/rtc_cm/terraform-azure-network-module.git"
- module.linuxservers.os
  Getting source "./os"

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "random" (1.3.1)...
- Downloading plugin for provider "azurerm" (0.3.3)...
`

If I try to force the use of azurerm latest version I get an error:

`No provider "azurerm" plugins meet the constraint "~> 0.3,~> 1.16".`

**Comment by juanjojulian** [comment]
More info...

juanjo@Dune testmodule$ git clone https://github.com/Azure/terraform-azurerm-compute.git
Clonando en 'terraform-azurerm-compute'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 278 (delta 11), reused 19 (delta 7), pack-reused 248
Recibiendo objetos: 100% (278/278), 64.44 KiB | 594.00 KiB/s, listo.
Resolviendo deltas: 100% (132/132), listo.

juanjo@Dune terraform-azurerm-compute$ git checkout v1.1.7
Nota: actualizando el árbol de trabajo 'v1.1.7'.

juanjo@Dune testmodule$ cd terraform-azurerm-compute/



juanjo@Dune terraform-azurerm-compute$ grep -A 3 provider main.tf 
provider "azurerm" {
  version = "~> 0.3"
}

--
provider "random" {
  version = "~> 1.0"
}

**Comment by metacpp** [comment]
@juanjojulian thanks for raising this issue. @jeffreyCline will help on the upgrading the minimum provider version in this module.
