### ISSUE TITLE
Explicit provider definition breaks multi subscription usage

### ISSUE THREAD

**Issue by LoboHacks** [Azure/terraform-azurerm-compute#84]
- Terraform Version: v0.11.10
- OS Version: Ubuntu 16.04

Bug description: Explicit provider definition in module breaks multi subscription usage.
In main.tf:
```tf
provider "azurerm" {
  version = ">= 1.1.0"
}
```
This overrides my implicit provider definition in the calling root module:
```tf
provider "azurerm" {
  subscription_id="${var.subscription_id}"
}
```
Resulting in some resources being created in another subscription and finally failing..

Steps to reproduce **not tested**:
1. Create two subscriptions
2. create RG in each with the same same e.g. server-rg
3. add a provider block for azure rm in the root module and pass subscriptions1 id as subscription_id parameter.
4. Example code
```tf
provider "azurerm" {
  alias           = "one"
  subscription_id = "Subscription1_ID"
}

provider "azurerm" {
  alias           = "two"
  subscription_id = "Subscription2_ID"
}

resource "azurerm_resource_group" "test1" {
  provider = "azure.one"
  name     = "server-rg"
  location = "West US"
}

resource "azurerm_resource_group" "test2" {
  provider = "azure.two"
  name     = "server-rg"
  location = "West US"
}

module "linuxservers1" {
  providers = {
    azurerm = "azurerm.one"
  }
  resource_group_name =  "server-rg"
  source         = "Azure/compute/azurerm"
  location       = "West US 2"
  vm_os_simple   = "UbuntuServer"
  public_ip_dns  = ["linsimplevmips"]                  // change to a unique name per datacenter region
  vnet_subnet_id = "${module.network.vnet_subnets[0]}"
}

module "linuxservers2" {
  providers = {
    azurerm = "azurerm.two"
  }
  resource_group_name =  "server-rg"
  source         = "Azure/compute/azurerm"
  location       = "West US 2"
  vm_os_simple   = "UbuntuServer"
  public_ip_dns  = ["linsimplevmips"]                  // change to a unique name per datacenter region
  vnet_subnet_id = "${module.network.vnet_subnets[0]}"
}
```
5. terraform apply

**Comment by LoboHacks** [comment]
Passing the provider config like in my example:
```tf
module "linuxservers2" {
  providers = {
    azurerm = "azurerm.two"
  }
```
actually works.

but having a general provider block like:
```tf
provider "azurerm" {
  subscription_id="${var.subscription_id}"
}
```

does not

**Comment by JunyiYi** [comment]
Hi @LoboHacks , thanks for reporting the problem. After taking a look, this one is not specific to this module, it is actually a common problem among all Azure terraform resources (I believe it could be reproduced even when you are using some simple raw resources like `azurerm_storage_account`).

Please create an issue in https://github.com/terraform-providers/terraform-provider-azurerm/issues instead.
