### ISSUE TITLE
Not able to output mac address

### ISSUE THREAD

**Issue by saiprasannasastry** [Azure/terraform-azurerm-compute#92]
i am passing the output as 

    output "mac" {
    value = "${azurerm_network_interface.ni.mac_address}"
   //value = "${azurerm_network_interface.ni.0.mac_address}"
    }

but both returns empty string, can someone point me how to get it

**Comment by yupwei68** [comment]
Hi @saiprasannasastry ,thanks for opening this issue. I'd like to encourage you to open an issue in https://github.com/terraform-providers/terraform-provider-azurerm/issues for resource `azurerm_network_interface`.

**Comment by yupwei68** [comment]
Hi @saiprasannasastry Sorry that I have to close this issue.
