### ISSUE TITLE
What if I want to destroy a specific VM after the deployment?

### ISSUE THREAD

**Issue by juanjojulian** [Azure/terraform-azurerm-compute#93]
For example, I use this module to create 5 linux VM's (nb_instances = "5") and after some time I want to remove one of them, but not the last one (number 5), I want to remove let's say VM number 2. If I'm not mistaken the only thing I can do here is lower the number of instances (nb_instances = "4") but this will remove instance number 5.

**Comment by yupwei68** [comment]
hi, thanks for this issue. You could use [`terrform destroy -target = [target resource]`](https://www.terraform.io/docs/commands/destroy.html). And sorry that I'm going to close this issue.
