### ISSUE TITLE
Not working with Terraform 0.12.0

### ISSUE THREAD

**Issue by src386** [Azure/terraform-azurerm-compute#99]
- Terraform Version: 0.12.0
- OS Version: Debian Stretch

Compute uses the "random" provider. However the version 1.0 it is not compatible with Terraform 0.12.0.

```
module "linuxservers" {
    source              = "Azure/compute/azurerm"
    version             = "1.2.1"
    location            = "France Central"
    resource_group_name = "terraform-demo-rg"
    vm_os_simple        = "UbuntuServer"
    public_ip_dns       = ["linsimplevmips"] // change to a unique name per datacenter region
    vnet_subnet_id      = "${module.network.vnet_subnets[0]}"
}
```

Then:
```
$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "random" v1.3.1 is not compatible with Terraform 0.12.0.

Provider version 2.1.0 is the earliest compatible version. Select it with 
the following version constraint:

        version = "~> 2.1"

Terraform checked all of the plugin versions matching the given constraint:
    ~> 1.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.


Error: incompatible provider version
```

**Comment by src386** [comment]
I ran the travis ci job and looks like it works with Terraform 0.11.7 mais you need to modify test/fixture/main.tf:

https://github.com/src386/terraform-azurerm-compute/blob/master/test/fixture/main.tf#L2

**Comment by src386** [comment]
Would you like a Merge Request ?

**Comment by scarolan** [comment]
Can confirm. My null_resource and random provider constraints are broken when I run this with TF 0.12.

**Comment by lmaule** [comment]
Also can confirm this. All we need is to update random provider version constraint to the last version and it will work with 0.12.1.

**Comment by jscheeres** [comment]
Any progress on this one?

**Comment by labewing** [comment]
Any updates on this issue?

**Comment by Xyon** [comment]
So this works with 0.12.3 now - I don't have 0.11 to test whether I broke it with that, though.

**Comment by jscheeres** [comment]
Red build on master

https://travis-ci.org/Azure/terraform-azurerm-compute/builds/556023670
